server:
  port: 9999

spring:
  # datasource
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ssg_shopping_cart?useUnicode=yes&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=Asia/Seoul
    username: ssg_admin
    password: 1234
  # JPA
  jpa:
    hibernate:
    ddl-auto: validate
    generate-ddl: false
    show-sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibernate:
        format_sql: true

# jasypt
jasypt:
  encryptor:
    password: ssg1234

jwt:
  secret: ssgjwt1234

# logging
logging:
  level:
    com.ssg.shoppingcart: debug
    org.hibernate: info
