server:
  port: 9999

spring:
  # datasource
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ENC(wtPXx6p8Qk/3C3BhODgX9FBMsCuO2AV/sRcP3AdSXDLT1/hkPHST4yg4Rqa49Pseeraub6vq+/3yes5CDWtbj8NqAh6/21eTBiH45+lXeFc7iO5JRz7FNwK4AWKmkLbIto/IqHLIIyDCOS2RsXeXuLJ7PBYU7PoUgQHiiVbGhpQoKBdsbsjobA==)
    username: ENC(aXpEoIWO5xRS4RrqpajFY821FhE7xZlm)
    password: ENC(kPvWTMvA09si7H5KeH9uaXopdCBpkbSD)
  # JPA
  jpa:
    hibernate:
    ddl-auto: validate
    generate-ddl: false
    show-sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibernate:
        format_sql: true

# jasypt
jasypt:
  encryptor:
    password: ${JASYPT_PASSWORD}

jwt:
  secret: ${JWT_SECRET}

# logging
logging:
  level:
    io.brothersoo.ecommerce.shoppingcart: debug
    org.hibernate: info
